### PR TITLE
feat: make the sitemap route configurable

### PR DESCRIPTION
**Pull request by timkley**
While using Prezet on my own site I saw the need to overwrite the route `prezet.show` with my own. When removing the route I ran into the error `Route [prezet.show] not defined.`.

This happens because the `UpdateSitemap` action depends on this route to be present.

I've added a configuration option to overwrite the default so prezet can work with a custom route.

### CODE REVIEW

**Comment by benbjurstrom** [comment]
The prezet.show route name is used in a few places that aren't published to userspace, for simplicity I'd prefer to keep referencing it without using a config.

If you really need to use a route name other then prezet.show it looks like you can use optional route parameters to create alternate names for the same route

```php
Route::get('prezet/{slug}/{clone1?}', ShowController::class)->name('prezet.show');
```

See https://laracasts.com/discuss/channels/laravel/multiple-routes-with-same-url-but-different-names

**Comment by timkley** [comment]
Hello!

After digging into this initial PR, I noticed that the `prezet` prefix is actually used across several controllers, which, in hindsight, makes my PR a bit redundant in its current form. It got me thinking that having customizable route names or a configurable prefix might be a helpful addition.

To give a bit of background on my setup: I have additional article-related routes beyond show and index and for consistency it would be fantastic to apply a unified prefix across all of them. While I could technically use `prezet` for everything, it might introduce some confusion, especially since the other routes aren’t using the Prezet package.

Totally understand your approach here, though, and it’s just a thought for potential future releases. I really appreciate the effort you’ve put into this package—it’s fantastic!

Thanks again, and keep up the great work!

**Comment by benbjurstrom** [comment]
I like the configurable prefix idea. Could maybe add a prezet_route() helper or something to avoid repeated references to the config.

**Comment by timkley** [comment]
That might be a good idea anyway, yes. Since it's a bigger change: do you want to tackle this yourself or would you be happy about a PR draft?

**Pull request closed without merging**
